# Generated by Django 5.0.6 on 2024-06-25 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testorder",
            name="product",
        ),
        migrations.AddField(
            model_name="testproduct",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="shop.testorder",
            ),
        ),
        migrations.AlterField(
            model_name="testorder",
            name="amount",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="testproduct",
            name="name",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="testproduct",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
