# Generated by Django 4.2 on 2023-04-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='redirect_counter',
            field=models.IntegerField(default=0),
        ),
    ]
