# Generated by Django 4.1.7 on 2023-04-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('F', 'Food'), ('E', 'Electronic'), ('C', 'Clothe'), ('B', 'Book'), ('O', 'Other')], max_length=10)),
            ],
        ),
    ]
