# Generated by Django 4.1.7 on 2023-02-25 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('86abf431-6ca5-4ff8-9dcf-c76f2fa0975a'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('details', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
