# Generated by Django 4.1.7 on 2023-02-25 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.UUIDField(default=uuid.UUID('27d13997-f391-4d79-b4b9-9e4b39aa4d77'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='GoalsList',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ac8d5550-1db8-44d6-bd28-ef878260e9ce'), editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
