# Generated by Django 4.1.7 on 2023-02-25 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_goal_id_goalslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7dba09c8-2bbc-4349-a927-e0e236491f67'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goalslist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('27bd94f6-2c3e-4188-aca8-9e7952ba1598'), editable=False, primary_key=True, serialize=False),
        ),
    ]
