# Generated by Django 4.1.7 on 2023-02-26 21:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_goal_user_alter_goal_id_alter_goalslist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1ebd13af-6fa2-4120-ae44-60786bd47482'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goalslist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0dcd60b6-2423-4569-aa3d-ce91bcb7cdbe'), editable=False, primary_key=True, serialize=False),
        ),
    ]
