# Generated by Django 4.1.7 on 2023-03-09 16:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_goal_id_alter_goalslist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd957f3a-1088-4848-af8e-f4a0299116d2'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goalslist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5413586b-8ca7-4858-9d8d-9a4f0c58e120'), editable=False, primary_key=True, serialize=False),
        ),
    ]
