# Generated by Django 4.1.7 on 2023-03-09 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_goal_id_alter_goalslist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='title',
        ),
        migrations.AlterField(
            model_name='goal',
            name='id',
            field=models.UUIDField(default=uuid.UUID('63866963-af8d-47d7-987f-9b1749ed4cbb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goalslist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2b1e6cb6-d8b6-43e5-9c55-b2fb927c6dae'), editable=False, primary_key=True, serialize=False),
        ),
    ]
