# Generated by Django 4.1.7 on 2023-03-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_goal_id_alter_goalslist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
