# Generated by Django 4.1.7 on 2023-03-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='titel',
            new_name='title',
        ),
    ]
