# Generated by Django 4.1.7 on 2023-03-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_titel_film_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
    ]
