# Generated by Django 4.1.7 on 2023-03-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[(1, 'Film'), (2, 'Book'), (3, 'Article')], max_length=7)),
                ('price', models.FloatField()),
                ('is_available', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[(1, 'Film'), (2, 'Book'), (3, 'Article')], max_length=7)),
                ('price', models.FloatField()),
                ('is_available', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[(1, 'Film'), (2, 'Book'), (3, 'Article')], max_length=7)),
                ('price', models.FloatField()),
                ('is_available', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
