# Generated by Django 4.1.7 on 2023-03-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_article_type_alter_book_type_alter_film_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.IntegerField(choices=[(1, 'Film'), (2, 'Book'), (3, 'Article')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.IntegerField(choices=[(1, 'Film'), (2, 'Book'), (3, 'Article')]),
        ),
        migrations.AlterField(
            model_name='film',
            name='type',
            field=models.IntegerField(choices=[(1, 'Film'), (2, 'Book'), (3, 'Article')]),
        ),
    ]
